name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: mvn test
